# CMake generated Testfile for 
# Source directory: /Users/liyinbin/github/gottingen/melon/test/fiber
# Build directory: /Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(fiber_cond_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_cond_test")
set_tests_properties(fiber_cond_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_dispatcher_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_dispatcher_test")
set_tests_properties(fiber_dispatcher_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_execution_queue_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_execution_queue_test")
set_tests_properties(fiber_execution_queue_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_fd_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_fd_test")
set_tests_properties(fiber_fd_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_futex_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_futex_test")
set_tests_properties(fiber_futex_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_key_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_key_test")
set_tests_properties(fiber_key_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_latch_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_latch_test")
set_tests_properties(fiber_latch_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_list_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_list_test")
set_tests_properties(fiber_list_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_mutex_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_mutex_test")
set_tests_properties(fiber_mutex_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_ping_pong_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_ping_pong_test")
set_tests_properties(fiber_ping_pong_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_runtime_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_runtime_test")
set_tests_properties(fiber_runtime_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_rwlock_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_rwlock_test")
set_tests_properties(fiber_rwlock_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_sched_yield_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_sched_yield_test")
set_tests_properties(fiber_sched_yield_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_test")
set_tests_properties(fiber_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_timer_thread_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_timer_thread_test")
set_tests_properties(fiber_timer_thread_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_token_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_token_test")
set_tests_properties(fiber_token_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_waitable_event_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_waitable_event_test")
set_tests_properties(fiber_waitable_event_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
add_test(fiber_work_stealing_queue_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/fiber/fiber_work_stealing_queue_test")
set_tests_properties(fiber_work_stealing_queue_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;13;add_test;/Users/liyinbin/github/gottingen/melon/test/fiber/CMakeLists.txt;0;")
