function(abel_debug)
    if (ABEL_STATUS_DEBUG)
        string(TIMESTAMP timestamp)
        if (ABEL_CACHE_RUN)
            set(type "DEBUG (CACHE RUN)")
        else ()
            set(type "DEBUG")
        endif ()
        message(STATUS "[abel *** ${type} *** ${timestamp}] ${ARGV}")
    endif ()
endfunction(abel_debug)

function(abel_print)
    if (ABEL_STATUS_PRINT OR ABEL_STATUS_DEBUG)
        if (ABEL_CACHE_RUN)
            hunter_status_debug("${ARGV}")
        else ()
            message(STATUS "[abel] ${ARGV}")
        endif ()
    endif ()
endfunction(abel_print)