name: melon-dev
channels:
  - conda-forge
  - mgottingen
  - defaults
dependencies:
  - ea-gtest
  - turbo
  - ea-gflags
  - ea-glog
  - ea-snappy
  - ea-leveldb
  - gperftools
  - ea-protobuf
  - openssl >=1.1.1a, <1.1.1z