# CMake generated Testfile for 
# Source directory: /Users/liyinbin/github/gottingen/melon/test/container
# Build directory: /Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(bounded_queue_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/bounded_queue_test")
set_tests_properties(bounded_queue_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(btree_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/btree_test")
set_tests_properties(btree_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(cache_bucket_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/cache_bucket_test")
set_tests_properties(cache_bucket_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(cache_item_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/cache_item_test")
set_tests_properties(cache_item_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(cache_lru_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/cache_lru_test")
set_tests_properties(cache_lru_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(cache_ram_policy_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/cache_ram_policy_test")
set_tests_properties(cache_ram_policy_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(case_ignored_flat_hash_map_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/case_ignored_flat_hash_map_test")
set_tests_properties(case_ignored_flat_hash_map_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(compressed_tuple_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/compressed_tuple_test")
set_tests_properties(compressed_tuple_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(container_memory_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/container_memory_test")
set_tests_properties(container_memory_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(containers_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/containers_test")
set_tests_properties(containers_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(dump_load_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/dump_load_test")
set_tests_properties(dump_load_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(find_cstr_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/find_cstr_test")
set_tests_properties(find_cstr_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(flat_hash_map_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/flat_hash_map_test")
set_tests_properties(flat_hash_map_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(flat_hash_set_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/flat_hash_set_test")
set_tests_properties(flat_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(flat_map_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/flat_map_test")
set_tests_properties(flat_map_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(hash_policy_testing_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/hash_policy_testing_test")
set_tests_properties(hash_policy_testing_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(hash_tables_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/hash_tables_test")
set_tests_properties(hash_tables_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(linked_list_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/linked_list_test")
set_tests_properties(linked_list_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(node_hash_map_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/node_hash_map_test")
set_tests_properties(node_hash_map_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(node_hash_policy_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/node_hash_policy_test")
set_tests_properties(node_hash_policy_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(node_hash_set_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/node_hash_set_test")
set_tests_properties(node_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(parallel_flat_hash_map_mutex_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/parallel_flat_hash_map_mutex_test")
set_tests_properties(parallel_flat_hash_map_mutex_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(parallel_flat_hash_map_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/parallel_flat_hash_map_test")
set_tests_properties(parallel_flat_hash_map_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(parallel_flat_hash_set_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/parallel_flat_hash_set_test")
set_tests_properties(parallel_flat_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(parallel_hash_map_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/parallel_hash_map_test")
set_tests_properties(parallel_hash_map_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(parallel_hash_set_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/parallel_hash_set_test")
set_tests_properties(parallel_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(parallel_node_hash_map_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/parallel_node_hash_map_test")
set_tests_properties(parallel_node_hash_map_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(parallel_node_hash_set_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/parallel_node_hash_set_test")
set_tests_properties(parallel_node_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(parallel_ring_queue_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/parallel_ring_queue_test")
set_tests_properties(parallel_ring_queue_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(raw_hash_set_allocator_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/raw_hash_set_allocator_test")
set_tests_properties(raw_hash_set_allocator_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
add_test(raw_hash_set_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/container/raw_hash_set_test")
set_tests_properties(raw_hash_set_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/container/CMakeLists.txt;0;")
