//
// Created by liyinbin on 2020/2/2.
//

#ifndef ABEL_ABEL_MEMORY_INTERNAL_ALLOC_FAILURE_INJECTOR_H_
#define ABEL_ABEL_MEMORY_INTERNAL_ALLOC_FAILURE_INJECTOR_H_

#endif //ABEL_ABEL_MEMORY_INTERNAL_ALLOC_FAILURE_INJECTOR_H_
