# CMake generated Testfile for 
# Source directory: /Users/liyinbin/github/gottingen/melon/test/rpc
# Build directory: /Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(rpc_adaptive_class_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_adaptive_class_test")
set_tests_properties(rpc_adaptive_class_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_builtin_service_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_builtin_service_test")
set_tests_properties(rpc_builtin_service_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_channel_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_channel_test")
set_tests_properties(rpc_channel_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_circuit_breaker_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_circuit_breaker_test")
set_tests_properties(rpc_circuit_breaker_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_controller_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_controller_test")
set_tests_properties(rpc_controller_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_esp_protocol_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_esp_protocol_test")
set_tests_properties(rpc_esp_protocol_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_event_dispatcher_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_event_dispatcher_test")
set_tests_properties(rpc_event_dispatcher_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_extension_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_extension_test")
set_tests_properties(rpc_extension_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_grpc_protocol_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_grpc_protocol_test")
set_tests_properties(rpc_grpc_protocol_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_h2_unsent_message_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_h2_unsent_message_test")
set_tests_properties(rpc_h2_unsent_message_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_hpack_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_hpack_test")
set_tests_properties(rpc_hpack_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_http_message_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_http_message_test")
set_tests_properties(rpc_http_message_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_http_parser_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_http_parser_test")
set_tests_properties(rpc_http_parser_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_http_rpc_protocol_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_http_rpc_protocol_test")
set_tests_properties(rpc_http_rpc_protocol_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_http_status_code_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_http_status_code_test")
set_tests_properties(rpc_http_status_code_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_hulu_prpc_protocol_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_hulu_prpc_protocol_test")
set_tests_properties(rpc_hulu_prpc_protocol_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_input_messenger_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_input_messenger_test")
set_tests_properties(rpc_input_messenger_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_load_balancer_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_load_balancer_test")
set_tests_properties(rpc_load_balancer_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_memcache_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_memcache_test")
set_tests_properties(rpc_memcache_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_mongo_protocol_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_mongo_protocol_test")
set_tests_properties(rpc_mongo_protocol_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_naming_service_filter_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_naming_service_filter_test")
set_tests_properties(rpc_naming_service_filter_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_naming_service_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_naming_service_test")
set_tests_properties(rpc_naming_service_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_nova_prpc_protocol_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_nova_prpc_protocol_test")
set_tests_properties(rpc_nova_prpc_protocol_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_prometheus_metrics_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_prometheus_metrics_test")
set_tests_properties(rpc_prometheus_metrics_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_proto_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_proto_test")
set_tests_properties(rpc_proto_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_protobuf_json_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_protobuf_json_test")
set_tests_properties(rpc_protobuf_json_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_public_prpc_protocol_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_public_prpc_protocol_test")
set_tests_properties(rpc_public_prpc_protocol_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_redis_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_redis_test")
set_tests_properties(rpc_redis_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_repeated_field_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_repeated_field_test")
set_tests_properties(rpc_repeated_field_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_rtmp_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_rtmp_test")
set_tests_properties(rpc_rtmp_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_server_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_server_test")
set_tests_properties(rpc_server_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_snappy_compress_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_snappy_compress_test")
set_tests_properties(rpc_snappy_compress_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_socket_map_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_socket_map_test")
set_tests_properties(rpc_socket_map_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_socket_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_socket_test")
set_tests_properties(rpc_socket_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_sofa_prpc_protocol_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_sofa_prpc_protocol_test")
set_tests_properties(rpc_sofa_prpc_protocol_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_ssl_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_ssl_test")
set_tests_properties(rpc_ssl_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_streaming_rpc_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_streaming_rpc_test")
set_tests_properties(rpc_streaming_rpc_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
add_test(rpc_uri_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/rpc/rpc_uri_test")
set_tests_properties(rpc_uri_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;11;add_test;/Users/liyinbin/github/gottingen/melon/test/rpc/CMakeLists.txt;0;")
