# CMake generated Testfile for 
# Source directory: /Users/liyinbin/github/gottingen/melon/test/strings
# Build directory: /Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ascii_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/ascii_test")
set_tests_properties(ascii_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(case_conv_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/case_conv_test")
set_tests_properties(case_conv_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(char_map_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/char_map_test")
set_tests_properties(char_map_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(char_traits_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/char_traits_test")
set_tests_properties(char_traits_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(charconv_bigint_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/charconv_bigint_test")
set_tests_properties(charconv_bigint_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(charconv_parse_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/charconv_parse_test")
set_tests_properties(charconv_parse_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(charconv_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/charconv_test")
set_tests_properties(charconv_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(compare_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/compare_test")
set_tests_properties(compare_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(contain_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/contain_test")
set_tests_properties(contain_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(ends_with_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/ends_with_test")
set_tests_properties(ends_with_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(numbers_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/numbers_test")
set_tests_properties(numbers_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(ostringstream_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/ostringstream_test")
set_tests_properties(ostringstream_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(resize_uninitialized_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/resize_uninitialized_test")
set_tests_properties(resize_uninitialized_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(starts_with_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/starts_with_test")
set_tests_properties(starts_with_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(str_cat_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/str_cat_test")
set_tests_properties(str_cat_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(str_join_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/str_join_test")
set_tests_properties(str_join_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(str_replace_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/str_replace_test")
set_tests_properties(str_replace_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(str_split_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/str_split_test")
set_tests_properties(str_split_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(strip_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/strip_test")
set_tests_properties(strip_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(trim_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/trim_test")
set_tests_properties(trim_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
add_test(utf8_test "/Users/liyinbin/github/gottingen/melon/-DCMAKE_PREFIX_PATH=~/miniconda3/envs/melon-dev/test/strings/utf8_test")
set_tests_properties(utf8_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;10;add_test;/Users/liyinbin/github/gottingen/melon/test/strings/CMakeLists.txt;0;")
